FROM amazonlinux

WORKDIR /app

COPY . /app

## php
RUN yum install -y httpd && \
    amazon-linux-extras install -y php7.2 && \
    yum install -y php php-pgsql

## python/hdf5

RUN yum install -y tar mkdir sudo which git wget openblas yum-utils gcc make 
RUN yum install -y zlib-devel openssl11-devel libffi-devel

RUN cd /app/misc; tar zxvf cpython-3.8.11.tar.gz;cd cpython-3.8.11; ./configure --prefix=/usr/local/python-3.8.11; make; make install

RUN sudo ln -s /usr/local/python-3.8.11/bin/python3.8 /usr/bin/python3
RUN python3 -m pip install setuptools wheel numpy netCDF4 

## build hdf5
RUN amazon-linux-extras install -y epel
RUN yum install –y epel-release
RUN yum-config-manager --enable epel
RUN yum install -y hdf5-devel

RUN python3 -m pip install h5py

## bring in the insar track data
RUN cd /app/web/cgm_data && \
    mkdir -p insar && \
    cd insar && \
    wget -nv https://g-c662a6.a78b8.36fe.data.globus.org/cxm/models/cgm/insar/D071_COMB_CGM_InSAR_v0_0_1.hdf5 && \
    wget -nv https://g-c662a6.a78b8.36fe.data.globus.org/cxm/models/cgm/insar/A166_COMB_CGM_InSAR_v0_0_1.hdf5 && \
    wget -nv https://g-c662a6.a78b8.36fe.data.globus.org/cxm/models/cgm/insar/A064_COMB_CGM_InSAR_v0_0_1.hdf5 && \
    wget -nv https://g-c662a6.a78b8.36fe.data.globus.org/cxm/models/cgm/insar/D173_COMB_CGM_InSAR_v0_0_1.hdf5

RUN cd /app && \
    git clone https://github.com/kmaterna/InSAR_CGM_readers_writers.git && \
    cd InSAR_CGM_readers_writers && \
    ./setup.py install && \ 
    chmod og+rw /app/web/result && \
    chmod -R og+x /app/web/py &&\
    cd /app

COPY ./doc/cgm.conf /etc/httpd/conf.d/

CMD ["apachectl", "-D", "FOREGROUND"]

