#!/bin/bash

dropdb --if-exists CGM2_db
createdb CGM2_db
mkdir -p /home/postgres/CGM
cp -Rv /app/schema/CGM_data /home/postgres/CGM
psql postgresql://postgres:example@localhost/CGM2_db << AAA

  CREATE EXTENSION postgis;
  SELECT PostGIS_Version();

  \i '/home/postgres/CGM/CGM_data/cgm_schema.sql';
  \i '/home/postgres/CGM/CGM_data/setup_cgm.sql';

DROP ROLE webonly;
CREATE ROLE webonly WITH LOGIN PASSWORD 'scec';
GRANT SELECT ON ALL TABLES IN SCHEMA public TO webonly;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;


  \dp
  \q

AAA
