#!/bin/bash

dropdb --if-exists CFM52_db 
createdb CFM52_db
mkdir -p /home/postgres/CFM
cp -Rv /app/schema /home/postgres/CFM/
psql postgresql://postgres:example@localhost/CFM52_db << AAA

  CREATE EXTENSION postgis;
  SELECT PostGIS_Version();

  \i '/home/postgres/CFM/schema/sql/CFM52_preferred_traces_nonblind.sql';
  \i '/home/postgres/CFM/schema/sql/CFM52_preferred_traces_blind.sql';
  \i '/home/postgres/CFM/schema/sql/setup_schema.sql';
  \i '/home/postgres/CFM/schema/sql/setup_tbs.sql';
  \i '/home/postgres/CFM/schema/sql/setup_object_tb.sql';
  \i '/home/postgres/CFM/schema/sql/linkup_traces.sql';
  \i '/home/postgres/CFM/schema/sql/add_foreign_key.sql';
  \i '/home/postgres/CFM/schema/sql/trace_merge.sql';

  SELECT UpdateGeometrySRID('trace_tb','geom',4326);

  \dp
  \q

AAA

dropdb --if-exists CGM1_db
createdb CGM1_db
mkdir -p /home/postgres/CGM
cp -Rv /app/schema/CGM_data /home/postgres/CGM
psql postgresql://postgres:example@localhost/CGM1_db << AAA

  CREATE EXTENSION postgis;
  SELECT PostGIS_Version();

  \i '/home/postgres/CGM/schema/sql/setup_cgm.sql';

  GRANT SELECT ON ALL TABLES IN SCHEMA public TO webonly;
  REVOKE CREATE ON SCHEMA public FROM PUBLIC;

  DROP ROLE webonly;
  CREATE ROLE webonly WITH LOGIN PASSWORD 'scec';
  GRANT SELECT ON ALL TABLES IN SCHEMA public TO webonly;
  REVOKE CREATE ON SCHEMA public FROM PUBLIC;

  \dp
  \q

AAA